stages:

  prepare:
    cmd:  python src/prepare.py

    deps:
      - data/data.csv
      - src/prepare.py

    outs:
      - data/processed.csv

  model:
    cmd: python src/model.py

    deps:
      - data/processed.csv
      
    outs:
      - data/model.pkl